service: serverless-clipboard
frameworkVersion: '2'

provider:
  name: aws
  runtime: java8
  lambdaHashingVersion: 20201221

# you can overwrite defaults here
#  stage: dev
  region: eu-central-1

# you can add packaging information here
package:
  artifact: target/hello-dev.jar

functions:
  saveOnClipboard:
    handler: com.serverless.Handler
    events:
      - httpApi:
          path: /save
          method: post
  getFromClipboard:
    handler: com.serverless.SecondHandler
    events:
      - httpApi:
          path: /get
          method: get

#    Define function environment variables here
#    environment:
#      variable2: value2

# you can add CloudFormation resource templates here
#resources:
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
